service: we45-sls-workshop-jwk
provider:
  name: aws
  runtime: python3.7
  memorySize: 2048
  timeout: 20
  stage: dev
  region: us-west-2

  # you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:*"
      Resource:
        - "*"

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
    usePipenv: false
    slim: true
    strip: false

functions:
  deserial:
    handler: handler.main
    timeout: 20
    events:
      - http:
          path: jwk
          method: get
          cors: true